language: csharp
sudo: required
dist: trusty
env:
  matrix:
  - DNX_VERSION=1.0.0-rc1-final DNX_USER_HOME=~/.dnx
mono:
- 4.0.5
os:
- linux
- osx
addons:
  apt:
    packages:
    # Packages required for android build
    - libc6-i386
    - lib32stdc++6
    - lib32gcc1
    - lib32ncurses5
    - lib32z1
    # Packages for DNX    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
install:
  # Install DNVM
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME
    DNX_BRANCH=v$DNX_VERSION sh
  - source $DNX_USER_HOME/dnvm/dnvm.sh
  - dnvm install $DNX_VERSION -r coreclr -alias default
  - dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default
  # Install npm
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
  - npm install -g npm@'>=1.4.3'
  - npm install
  # Install ruby dependencies
  - rvm use 2.2.1 --install --binary --fuzzy
  - gem install bundler
  - bundle install
  # Install android SDK
  - mkdir android
  - wget -qO- "http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz" | tar -zxv -C ./android
  - echo y | ./android/android-sdk-linux/tools/android update sdk --all --filter platform-tools,android-23,build-tools-23.0.1,extra-android-support,extra-android-m2repository,extra-google-m2repository --no-ui --force
  - export ANDROID_HOME=`pwd`/android/android-sdk-linux
script:
  - gulp
after_script:
  - echo "========== Server log: ============"
  - pwd
  - ls -al
  - ls -al TestResults
  - cat TestResults/*.log
notifications:
  slack:
    secure: d0PFVLcyqcMxNtmZ8JaEpIBzXbUbZCgKs8QtBB5qEIXDnxflSR3AhczlILNhTBKtMEBlwVzsz65yP09XcmvB6xpAfJbHqSRzk2frKa5viPcAD8Wr/NYamt9/UiTCsnql8MqzjVy0tLdMscXKRmsUey4YF570zl0b7gAbq7XTqxM=
