parser: "@typescript-eslint/parser"
extends:
  - "../../../.default-eslintrc.yaml"

plugins:
  - import

rules:
  no-console: warn

  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-unused-vars": off
  import/no-default-export: warn
  import/no-self-import: warn # This cause many circular dependency issues with index files.
  import/no-internal-modules: off
  import/order:
    - warn
    - groups: ["builtin", "external", "parent", "sibling", "index"]
      alphabetize:
        order: "asc"
        caseInsensitive: true
