# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: main
    displayName: "Build and test"
    steps:
      - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          - template: ./templates/verify-changes.yaml

      - template: ./templates/build.yaml

      - script: npx @microsoft/rush test:ci -v
        displayName: Test

      - script: npx @microsoft/rush lint -v
        displayName: Lint

      - script: npx @microsoft/rush publish --publish --pack --include-all
        displayName: Pack packages

      - publish: $(Build.SourcesDirectory)/common/temp/artifacts/packages
        artifact: packages
        displayName: Publish packages(.tgz) as pipeline artifacts

      - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          - template: ./templates/create-tryit-comment.yaml

  - job: regressiontests
    displayName: Regression tests
    dependsOn: main
    steps:
      - template: ./templates/regression-tests.yaml

  - job: lintdocs
    displayName: Lint docs
    steps:
      - script: |
          sudo npm install -g markdown-link-check
          find docs -name "*.md" -print0 | xargs -0  -n1 markdown-link-check -c ./markdown-link-check-config.json
        displayName: Find
