# Template for building projects
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g npm
      npx @microsoft/rush update
    displayName: "Install dependencies"

  - script: |
      npx @microsoft/rush rebuild
    displayName: "Build"

