---
__info: yaml
__status: {}
azure-arm: true
azure-validator: true
azure-validator-composed:
  merge-state: composed
azure-validator-individual:
  merge-state: individual
base-folder: .
clear-output-folder: {}
client-side-validation: true
csharp:
  output-folder: Client
debug: false
declare-directive:
  remove-operation: |-
    {
      from: 'swagger-document',
      "where-operation": $,
      transform: 'return undefined'
    }
  set: '{ transform: `return ${JSON.stringify($)}` }'
  where-operation: |-
    (() => {
      switch ($context.from) {
        case "code-model-v1":
          return { from: "code-model-v1", where: `$.operations[*].methods[?(@.serializedName == ${JSON.stringify($)})]` };
        case "swagger-document":
        default:
          return { from: "swagger-document", where: `$.paths.*[?(@.operationId == ${JSON.stringify($)})]` };
      }
    })()
directive:
  - from: storage.json
    reason: We've experienced a lack of cowbell in storage account names.
    set: >-
      Checks that the account name has sufficient cowbell (in order to prevent
      fevers).
    where: >-
      $.paths["/subscriptions/{subscriptionId}/providers/Microsoft.Storage/checkNameAvailability"].post.description
  - from: storage.json
    reason: Make sure people know.
    transform: $ += " Make sure you add that extra cowbell."
    where: >-
      $.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}"].put.description
  - from: storage.json
    reason: >-
      Our new guidelines require upper case descriptions here. Customers love
      it.
    transform: return $.toUpperCase()
    where: $.definitions.Usage.description
  - from: swagger-document
    reason: I don't like plural.
    transform: 'return $.replace(/ies$/, "y")'
    where: $.paths..operationId
  - from: code-model-v1
    reason: We wanna group methods by URI.
    transform: >
      const url = $.methods[0]["url"]; const res =
      url.split("/Microsoft.Storage/")[1].split("/")[0]; $.name.raw = res;
      $.summary = JSON.stringify($, null, 2);
    where: '$.operations[*]'
  - from: swagger-document
    reason: polyfill
    transform: |
      return typeof $ === "boolean"
        ? ($ ? { type: "object" } : undefined)
        : $
    where: $.definitions.*.additionalProperties
disable-validation: false
help-content:
  csharp:
    activationScope: csharp
    categoryFriendlyName: 'C# Generator'
    settings:
      - description: generate code in Azure flavor
        key: azure-arm
      - description: generate code in fluent flavor
        key: fluent
      - description: determines the root namespace to be used in generated code
        key: namespace
        required: true
        type: string
      - description: >-
          text to include as a header comment in generated files (magic strings:
          MICROSOFT_MIT, MICROSOFT_APACHE, MICROSOFT_MIT_NO_VERSION,
          MICROSOFT_APACHE_NO_VERSION, MICROSOFT_MIT_NO_CODEGEN)
        key: license-header
        type: string
      - description: >-
          max. number of properties in a request body. If the number of
          properties in the request body is less than or equal to this value,
          these properties will be represented as individual method arguments
          instead
        key: payload-flattening-threshold
        type: number
      - description: >-
          include a credential property and constructor parameter supporting
          different authentication behaviors
        key: add-credentials
      - description: >-
          overrides the name of the client class (usually derived from
          $.info.title)
        key: override-client-name
        type: string
      - description: >-
          generate constructors with internal instead of public visibility
          (useful for convenience layers)
        key: use-internal-constructors
      - description: >-
          determines amount of synchronous wrappers to generate; default:
          essential
        key: sync-methods
        type: '"essential" | "all" | "none"'
      - description: use DateTimeOffset instead of DateTime to model date/time types
        key: use-datetimeoffset
      - description: >-
          whether to validate parameters at the client side (according to
          OpenAPI definition) before making a request; default: true
        key: client-side-validation
        type: boolean
      - description: maximum line width of comments before breaking into a new line
        key: max-comment-columns
        type: number
      - description: >-
          generate all code into the specified, single file (instead of the
          usual folder structure)
        key: output-file
        type: string
      - description: generate sample code from x-ms-examples (experimental)
        key: sample-generation
input-file:
  - >-
    https://github.com/Azure/azure-rest-api-specs/blob/d374d03801e97737ddb32e01f20513e7b2bbd9c3/arm-storage/2015-06-15/swagger/storage.json
no-upgrade-check: {}
openapi-type: arm
output-artifact:
  - swagger-document.json
  - code-model-v1.yaml
  - pipeline.yaml
  - configuration.yaml
  - source-file-csharp
  - source-file-jsonrpcclient
output-folder: generated
perform-load: true
pipeline:
  configuration-emitter:
    scope: scope-configuration-emitter
    suffixes:
      - ''
  csharp/cm/emitter:
    input: transform
    scope: scope-cm/emitter
    suffixes:
      - ''
  csharp/cm/transform:
    input: commonmarker
    output-artifact: code-model-v1
    suffixes:
      - ''
  csharp/commonmarker:
    input: imodeler1
    output-artifact: code-model-v1
    suffixes:
      - ''
  csharp/emitter:
    input: transform
    scope: scope-csharp/emitter
    suffixes:
      - ''
  csharp/generate:
    input: cm/transform
    output-artifact: source-file-csharp
    plugin: csharp
    suffixes:
      - ''
  csharp/imodeler1:
    input: openapi-document/identity
    output-artifact: code-model-v1
    scope: csharp
    suffixes:
      - ''
  csharp/simplifier:
    input: generate
    output-artifact: source-file-csharp
    plugin: csharp-simplifier
    suffixes:
      - ''
  csharp/transform:
    input: simplifier
    output-artifact: source-file-csharp
    scope: scope-transform-string
    suffixes:
      - ''
  jsonrpcclient/emitter:
    input: transform
    scope: scope-jsonrpcclient/emitter
    suffixes: []
  jsonrpcclient/generate:
    input: imodeler1
    output-artifact: source-file-jsonrpcclient
    plugin: jsonrpcclient
    suffixes: []
  jsonrpcclient/imodeler1:
    input: openapi-document/identity
    output-artifact: code-model-v1
    scope: jsonrpcclient
    suffixes: []
  jsonrpcclient/transform:
    input: generate
    output-artifact: source-file-jsonrpcclient
    scope: scope-transform-string
    suffixes: []
  openapi-document/emitter:
    input: identity
    scope: scope-openapi-document/emitter
    suffixes:
      - ''
  openapi-document/identity:
    input: transform
    output-artifact: openapi-document
    suffixes:
      - ''
  openapi-document/openapi-document-converter:
    input: swagger-document/identity
    output-artifact: openapi-document
    suffixes:
      - ''
  openapi-document/transform:
    input: openapi-document-converter
    output-artifact: openapi-document
    suffixes:
      - ''
  pipeline-emitter:
    scope: scope-pipeline-emitter
    suffixes:
      - ''
  swagger-document-override/md-override-loader:
    output-artifact: immediate-config
    scope: perform-load
    suffixes:
      - ''
  swagger-document/classic-openapi-validator:
    input: swagger-document/identity
    scope: azure-validator-composed
    suffixes:
      - ''
  swagger-document/compose:
    input: individual/identity
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/emitter:
    input: identity
    scope: scope-swagger-document/emitter
    suffixes:
      - ''
  swagger-document/identity:
    input: transform
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/individual/classic-openapi-validator:
    input: swagger-document/individual/identity
    scope: azure-validator-individual
    suffixes:
      - ''
  swagger-document/individual/identity:
    input: transform
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/individual/openapi-validator:
    input: swagger-document/individual/identity
    scope: azure-validator-individual
    suffixes:
      - ''
  swagger-document/individual/transform:
    input: loader
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/loader:
    output-artifact: swagger-document
    scope: perform-load
    suffixes:
      - ''
  swagger-document/model-validator:
    input: swagger-document/identity
    scope: model-validator
    suffixes: []
  swagger-document/openapi-validator:
    input: swagger-document/identity
    scope: azure-validator-composed
    suffixes:
      - ''
  swagger-document/reflect-api-versions-cs:
    input:
      - identity
      - individual/identity
      - csharp/emitter
    scope: reflect-api-versions
    suffixes: []
  swagger-document/reflect-api-versions-cs/emitter:
    input: reflect-api-versions-cs
    scope: scope-reflect-api-versions-cs-emitter
    suffixes: []
  swagger-document/semantic-validator:
    input: swagger-document/identity
    scope: semantic-validator
    suffixes: []
  swagger-document/transform:
    input: transform-immediate
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/transform-immediate:
    input:
      - swagger-document-override/md-override-loader
      - compose
    output-artifact: swagger-document
    suffixes:
      - ''
require: []
scope-cm-yaml/emitter:
  input-artifact: code-model-v1-yaml
  is-object: true
  output-uri-expr: |
    "code-model-v1-yaml"
scope-cm/emitter:
  input-artifact: code-model-v1
  is-object: true
  output-uri-expr: |
    "code-model-v1"
scope-configuration-emitter:
  input-artifact: configuration
  is-object: true
  output-uri-expr: |
    "configuration"
scope-csharp/emitter:
  input-artifact: source-file-csharp
scope-jsonrpcclient/emitter:
  input-artifact: source-file-jsonrpcclient
scope-openapi-document/emitter:
  input-artifact: openapi-document
  is-object: true
  output-uri-expr: >
    $config["output-file"] || 

    ($config.namespace ? $config.namespace.replace(/:/g,'_') : undefined) || 

    $config["input-file"][0].split('/').reverse()[0].split('\\').reverse()[0].replace(/\.json$/,
    "")
scope-pipeline-emitter:
  input-artifact: pipeline
  is-object: true
  output-uri-expr: |
    "pipeline"
scope-reflect-api-versions-cs-emitter:
  input-artifact: source-file-csharp
  output-uri-expr: $key
scope-swagger-document/emitter:
  input-artifact: swagger-document
  is-object: true
  output-uri-expr: >
    $config["output-file"] || 

    ($config.namespace ? $config.namespace.replace(/:/g,'_') : undefined) || 

    $config["input-file"][0].split('/').reverse()[0].split('\\').reverse()[0].replace(/\.json$/,
    "")
scope-transform-string:
  is-object: false
skip-upgrade-check: {}
use: []
use-extension:
  '@microsoft.azure/autorest.csharp': ~2.2.45
  '@microsoft.azure/autorest.modeler': 2.3.38
  '@microsoft.azure/classic-openapi-validator': ~1.0.3
  '@microsoft.azure/openapi-validator': ~1.0.0
used-extension:
  - '["@microsoft.azure/autorest.csharp","~2.2.45"]'
  - '["@microsoft.azure/classic-openapi-validator","~1.0.3"]'
  - '["@microsoft.azure/openapi-validator","~1.0.0"]'
  - '["@microsoft.azure/autorest.modeler","2.3.38"]'
verbose: false

