---
pipeline-emitter:
  pluginName: pipeline-emitter
  configScope:
    - scope-pipeline-emitter
  inputs: []
configuration-emitter:
  pluginName: configuration-emitter
  configScope:
    - scope-configuration-emitter
  inputs: []
swagger-document-override/md-override-loader:
  pluginName: md-override-loader
  outputArtifact: immediate-config
  configScope: []
  inputs: []
swagger-document/loader:
  pluginName: loader
  outputArtifact: swagger-document
  configScope: []
  inputs: []
swagger-document/individual/transform:
  pluginName: transform
  outputArtifact: swagger-document
  configScope: []
  inputs:
    - swagger-document/loader
swagger-document/individual/identity:
  pluginName: identity
  outputArtifact: swagger-document
  configScope: []
  inputs:
    - swagger-document/individual/transform
swagger-document/compose:
  pluginName: compose
  outputArtifact: swagger-document
  configScope: []
  inputs:
    - swagger-document/individual/identity
swagger-document/transform-immediate:
  pluginName: transform-immediate
  outputArtifact: swagger-document
  configScope: []
  inputs:
    - swagger-document-override/md-override-loader
    - swagger-document/compose
swagger-document/transform:
  pluginName: transform
  outputArtifact: swagger-document
  configScope: []
  inputs:
    - swagger-document/transform-immediate
swagger-document/identity:
  pluginName: identity
  outputArtifact: swagger-document
  configScope: []
  inputs:
    - swagger-document/transform
swagger-document/emitter:
  pluginName: emitter
  configScope:
    - scope-swagger-document/emitter
  inputs:
    - swagger-document/transform
csharp/modeler:
  pluginName: modeler
  outputArtifact: code-model-v1
  configScope:
    - csharp
  inputs:
    - swagger-document/identity
csharp/commonmarker:
  pluginName: commonmarker
  outputArtifact: code-model-v1
  configScope:
    - csharp
  inputs:
    - csharp/modeler
csharp/cm/transform:
  pluginName: transform
  outputArtifact: code-model-v1
  configScope:
    - csharp
  inputs:
    - csharp/commonmarker
csharp/cm/emitter:
  pluginName: emitter
  configScope:
    - csharp
    - scope-cm/emitter
  inputs:
    - csharp/cm/transform
csharp/generate:
  pluginName: csharp
  outputArtifact: source-file-csharp
  configScope:
    - csharp
  inputs:
    - csharp/cm/transform
csharp/simplifier:
  pluginName: csharp-simplifier
  outputArtifact: source-file-csharp
  configScope:
    - csharp
  inputs:
    - csharp/generate
csharp/transform:
  pluginName: transform
  outputArtifact: source-file-csharp
  configScope:
    - csharp
    - scope-transform-string
  inputs:
    - csharp/simplifier
csharp/emitter:
  pluginName: emitter
  configScope:
    - csharp
    - scope-transform-string
    - scope-csharp/emitter
  inputs:
    - csharp/transform
swagger-document/classic-openapi-validator:
  pluginName: classic-openapi-validator
  configScope:
    - azure-validator-composed
  inputs:
    - swagger-document/identity
swagger-document/individual/classic-openapi-validator:
  pluginName: classic-openapi-validator
  configScope:
    - azure-validator-individual
  inputs:
    - swagger-document/individual/identity
swagger-document/openapi-validator:
  pluginName: openapi-validator
  configScope:
    - azure-validator-composed
  inputs:
    - swagger-document/identity
swagger-document/individual/openapi-validator:
  pluginName: openapi-validator
  configScope:
    - azure-validator-individual
  inputs:
    - swagger-document/individual/identity
