---
configuration-emitter:
  configScope:
    - scope-configuration-emitter
  inputs: []
  pluginName: configuration-emitter
csharp/cm/emitter:
  configScope:
    - csharp
    - scope-cm/emitter
  inputs:
    - csharp/cm/transform
  pluginName: emitter
csharp/cm/transform:
  configScope:
    - csharp
  inputs:
    - csharp/commonmarker
  outputArtifact: code-model-v1
  pluginName: transform
csharp/commonmarker:
  configScope:
    - csharp
  inputs:
    - csharp/imodeler1
  outputArtifact: code-model-v1
  pluginName: commonmarker
csharp/emitter:
  configScope:
    - csharp
    - scope-transform-string
    - scope-csharp/emitter
  inputs:
    - csharp/transform
  pluginName: emitter
csharp/generate:
  configScope:
    - csharp
  inputs:
    - csharp/cm/transform
  outputArtifact: source-file-csharp
  pluginName: csharp
csharp/imodeler1:
  configScope:
    - csharp
  inputs:
    - openapi-document/identity
  outputArtifact: code-model-v1
  pluginName: imodeler1
csharp/simplifier:
  configScope:
    - csharp
  inputs:
    - csharp/generate
  outputArtifact: source-file-csharp
  pluginName: csharp-simplifier
csharp/transform:
  configScope:
    - csharp
    - scope-transform-string
  inputs:
    - csharp/simplifier
  outputArtifact: source-file-csharp
  pluginName: transform
openapi-document/emitter:
  configScope:
    - scope-openapi-document/emitter
  inputs:
    - openapi-document/identity
  pluginName: emitter
openapi-document/identity:
  configScope: []
  inputs:
    - openapi-document/transform
  outputArtifact: openapi-document
  pluginName: identity
openapi-document/openapi-document-converter:
  configScope: []
  inputs:
    - swagger-document/identity
  outputArtifact: openapi-document
  pluginName: openapi-document-converter
openapi-document/transform:
  configScope: []
  inputs:
    - openapi-document/openapi-document-converter
  outputArtifact: openapi-document
  pluginName: transform
pipeline-emitter:
  configScope:
    - scope-pipeline-emitter
  inputs: []
  pluginName: pipeline-emitter
swagger-document-override/md-override-loader:
  configScope: []
  inputs: []
  outputArtifact: immediate-config
  pluginName: md-override-loader
swagger-document/classic-openapi-validator:
  configScope:
    - azure-validator-composed
  inputs:
    - swagger-document/identity
  pluginName: classic-openapi-validator
swagger-document/compose:
  configScope: []
  inputs:
    - swagger-document/individual/identity
  outputArtifact: swagger-document
  pluginName: compose
swagger-document/emitter:
  configScope:
    - scope-swagger-document/emitter
  inputs:
    - swagger-document/identity
  pluginName: emitter
swagger-document/identity:
  configScope: []
  inputs:
    - swagger-document/transform
  outputArtifact: swagger-document
  pluginName: identity
swagger-document/individual/classic-openapi-validator:
  configScope:
    - azure-validator-individual
  inputs:
    - swagger-document/individual/identity
  pluginName: classic-openapi-validator
swagger-document/individual/identity:
  configScope: []
  inputs:
    - swagger-document/individual/transform
  outputArtifact: swagger-document
  pluginName: identity
swagger-document/individual/openapi-validator:
  configScope:
    - azure-validator-individual
  inputs:
    - swagger-document/individual/identity
  pluginName: openapi-validator
swagger-document/individual/transform:
  configScope: []
  inputs:
    - swagger-document/loader
  outputArtifact: swagger-document
  pluginName: transform
swagger-document/loader:
  configScope: []
  inputs: []
  outputArtifact: swagger-document
  pluginName: loader
swagger-document/openapi-validator:
  configScope:
    - azure-validator-composed
  inputs:
    - swagger-document/identity
  pluginName: openapi-validator
swagger-document/transform:
  configScope: []
  inputs:
    - swagger-document/transform-immediate
  outputArtifact: swagger-document
  pluginName: transform
swagger-document/transform-immediate:
  configScope: []
  inputs:
    - swagger-document-override/md-override-loader
    - swagger-document/compose
  outputArtifact: swagger-document
  pluginName: transform-immediate
