---
swagger-document-override/md-override-loader:
  pluginName: md-override-loader
  outputArtifact: immediate-config
  configScope:
    - perform-load
  inputs: []
swagger-document/loader:
  pluginName: loader
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs: []
swagger-document/individual/transform:
  pluginName: transform
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs:
    - swagger-document/loader
swagger-document/individual/schema-validator:
  pluginName: schema-validator
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs:
    - swagger-document/individual/transform
swagger-document/individual/identity:
  pluginName: identity
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs:
    - swagger-document/individual/schema-validator
swagger-document/compose:
  pluginName: compose
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs:
    - swagger-document/individual/identity
swagger-document/transform-immediate:
  pluginName: transform-immediate
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs:
    - swagger-document-override/md-override-loader
    - swagger-document/compose
swagger-document/transform:
  pluginName: transform
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs:
    - swagger-document/transform-immediate
swagger-document/identity:
  pluginName: identity
  outputArtifact: swagger-document
  configScope:
    - perform-load
  inputs:
    - swagger-document/transform
openapi-document/openapi-document-converter:
  pluginName: openapi-document-converter
  outputArtifact: openapi-document
  configScope:
    - perform-load
  inputs:
    - swagger-document/identity
openapi-document/transform:
  pluginName: transform
  outputArtifact: openapi-document
  configScope:
    - perform-load
  inputs:
    - openapi-document/openapi-document-converter
openapi-document/component-modifiers:
  pluginName: component-modifiers
  outputArtifact: openapi-document
  configScope:
    - perform-load
  inputs:
    - openapi-document/transform
openapi-document/identity:
  pluginName: identity
  outputArtifact: openapi-document
  configScope:
    - perform-load
  inputs:
    - openapi-document/component-modifiers
csharp/imodeler1:
  pluginName: imodeler1
  outputArtifact: code-model-v1
  configScope:
    - perform-load
    - csharp
  inputs:
    - openapi-document/identity
csharp/commonmarker:
  pluginName: commonmarker
  outputArtifact: code-model-v1
  configScope:
    - perform-load
    - csharp
  inputs:
    - csharp/imodeler1
csharp/cm/transform:
  pluginName: transform
  outputArtifact: code-model-v1
  configScope:
    - perform-load
    - csharp
  inputs:
    - csharp/commonmarker
csharp/generate:
  pluginName: csharp
  outputArtifact: source-file-csharp
  configScope:
    - perform-load
    - csharp
  inputs:
    - csharp/cm/transform
csharp/simplifier:
  pluginName: csharp-simplifier
  outputArtifact: source-file-csharp
  configScope:
    - perform-load
    - csharp
  inputs:
    - csharp/generate
csharp/transform:
  pluginName: transform
  outputArtifact: source-file-csharp
  configScope:
    - perform-load
    - csharp
    - scope-transform-string
  inputs:
    - csharp/simplifier
csharp/emitter:
  pluginName: emitter
  configScope:
    - perform-load
    - csharp
    - scope-transform-string
    - scope-csharp/emitter
  inputs:
    - csharp/transform
pipeline-emitter:
  pluginName: pipeline-emitter
  configScope:
    - scope-pipeline-emitter
  inputs: []
configuration-emitter:
  pluginName: configuration-emitter
  configScope:
    - scope-configuration-emitter
  inputs: []
swagger-document/emitter:
  pluginName: emitter
  configScope:
    - perform-load
    - scope-swagger-document/emitter
  inputs:
    - swagger-document/identity
openapi-document/emitter:
  pluginName: emitter
  configScope:
    - perform-load
    - scope-openapi-document/emitter
  inputs:
    - openapi-document/identity
csharp/cm/emitter:
  pluginName: emitter
  configScope:
    - perform-load
    - csharp
    - scope-cm/emitter
  inputs:
    - csharp/cm/transform
swagger-document/classic-openapi-validator:
  pluginName: classic-openapi-validator
  configScope:
    - perform-load
    - azure-validator-composed
  inputs:
    - swagger-document/identity
swagger-document/individual/classic-openapi-validator:
  pluginName: classic-openapi-validator
  configScope:
    - perform-load
    - azure-validator-individual
  inputs:
    - swagger-document/individual/identity
swagger-document/openapi-validator:
  pluginName: openapi-validator
  configScope:
    - perform-load
    - azure-validator-composed
  inputs:
    - swagger-document/identity
swagger-document/individual/openapi-validator:
  pluginName: openapi-validator
  configScope:
    - perform-load
    - azure-validator-individual
  inputs:
    - swagger-document/individual/identity
